# Generated by Django 5.0.14 on 2026-10-06 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lessons_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.IntegerField()),
                ('courses_course', models.ForeignKey(db_column='courses_course_id', on_delete=django.db.models.deletion.CASCADE, to='learniva_app.courses')),
            ],
            options={
                'verbose_name_plural': 'Lessons',
                'db_table': 'lessons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('questions_count', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('lessons_lessons', models.ForeignKey(db_column='lessons_lessons_id', on_delete=django.db.models.deletion.CASCADE, to='learniva_app.lessons')),
            ],
            options={
                'verbose_name_plural': 'Tests',
                'db_table': 'tests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('complete_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learniva_app.tests')),
            ],
            options={
                'verbose_name_plural': 'Test_results',
                'db_table': 'test_results',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=255)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=100)),
                ('order_number', models.IntegerField()),
                ('tests_test', models.ForeignKey(db_column='tests_test_id', on_delete=django.db.models.deletion.CASCADE, to='learniva_app.tests')),
            ],
            options={
                'verbose_name_plural': 'questions',
                'db_table': 'questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('user_courses_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learniva_app.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User_courses',
                'db_table': 'user_courses',
            },
        ),
    ]
