# Generated by Django 5.0.14 on 2026-09-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('decription', models.TextField(blank=True, null=True)),
                ('categoty', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lessons_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.IntegerField()),
                ('courses_course', models.ForeignKey(db_column='courses_course_id', on_delete=django.db.models.deletion.CASCADE, to='learniva_app.courses')),
            ],
            options={
                'db_table': 'lessons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('questions_count', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('lessons_lessons', models.ForeignKey(db_column='lessons_lessons_id', on_delete=django.db.models.deletion.CASCADE, to='learniva_app.lessons')),
            ],
            options={
                'db_table': 'tests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=255)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=100)),
                ('order_number', models.IntegerField()),
                ('tests_test', models.ForeignKey(db_column='tests_test_id', on_delete=django.db.models.deletion.CASCADE, to='learniva_app.tests')),
            ],
            options={
                'db_table': 'questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('user_courses_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='learniva_app.courses')),
                ('users_user', models.ForeignKey(db_column='users_user_id', on_delete=django.db.models.deletion.CASCADE, to='learniva_app.users')),
            ],
            options={
                'db_table': 'user_courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('complete_at', models.DateTimeField(auto_now_add=True)),
                ('tests_test', models.ForeignKey(db_column='tests_test_id', on_delete=django.db.models.deletion.CASCADE, to='learniva_app.tests')),
                ('users_user', models.ForeignKey(db_column='users_user_id', on_delete=django.db.models.deletion.CASCADE, to='learniva_app.users')),
            ],
            options={
                'db_table': 'test_results',
                'managed': True,
            },
        ),
    ]
