# Generated by Django 5.0.14 on 2026-09-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learniva_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'managed': True, 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'managed': True, 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'managed': True, 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='testresults',
            options={'managed': True, 'verbose_name_plural': 'Test_results'},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'managed': True, 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='usercourses',
            options={'managed': True, 'verbose_name_plural': 'User_courses'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True, 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='categoty',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='decription',
            new_name='description',
        ),
    ]
